import React,{useState,useId} from 'react';
import {Range,LabTitle,Chart,format} from './ui.jsx';
export function useParams(initial){const [p,set]=useState(initial);return [p,(key,label,min,max,step=1,suffix='')=><Range key={key} label={label} value={p[key]} onChange={value=>set(old=>({...old,[key]:value}))} min={min} max={max} step={step} suffix={suffix}/>,(key,value)=>set(old=>({...old,[key]:value})),()=>set(initial)];}
export function Choice({label,value,onChange,options}){const id=useId();return <div className="viz-choice"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,text])=><option key={v} value={v}>{text}</option>)}</select></div>;}
export function Shell({title,question,reset,children,note}){return <section className="lab viz-lab" aria-label={title}><LabTitle title={title}>{question}</LabTitle><button className="viz-reset" onClick={reset}>Reset</button>{children}<p className="lab-note">{note}</p></section>;}
export function Stats({items}){return <div className="results viz-stats" aria-live="polite">{items.map(([label,value,unit])=><div key={label}><span>{label}</span><strong>{typeof value==='number'?format(value,3):value}</strong><p>{unit}</p></div>)}</div>;}
export function Plot({title,xLabel,yLabel,series,markers=[],digits=2,includeZero=true,verticals=[]}){
 const xs=series.flatMap(s=>s.values.map(v=>v[0])),ys=series.flatMap(s=>s.values.map(v=>v[1]));
 const lo=includeZero?Math.min(0,...ys):Math.min(...ys),hi=includeZero?Math.max(0,...ys):Math.max(...ys),pad=Math.max((hi-lo)*.08,1e-5);
 const bounds=[includeZero&&lo>=0?0:lo-pad,hi+pad];
 return <><div className="viz-legend">{series.map((s,i)=><span key={s.name}><i className={`viz-key viz-key-${i}`} aria-hidden="true"/>{s.name}</span>)}</div><Chart title={title} description={series.map(s=>s.name).join(' เทียบกับ ')} xLabel={xLabel} yLabel={yLabel} xDomain={[Math.min(...xs),Math.max(...xs)]} yDomain={bounds} lines={series.map((s,i)=>({values:s.values,className:`viz-line-${i}`}))} markers={markers} verticals={verticals} xFormat={v=>format(v,0)} yFormat={v=>format(v,digits)}/><details className="viz-data"><summary>ดูค่าตัวอย่างจากกราฟ</summary><div className="table-scroll" tabIndex="0" role="region" aria-label="ค่าตัวอย่างจากกราฟ"><table><thead><tr><th>{xLabel}</th>{series.map(s=><th key={s.name}>{s.name}</th>)}</tr></thead><tbody>{series[0].values.filter((_,i)=>i%Math.max(1,Math.floor((series[0].values.length-1)/8))===0).map(([x])=><tr key={x}><th>{format(x,2)}</th>{series.map(s=><td key={s.name}>{format(s.values.find(v=>v[0]===x)?.[1]??0,Math.max(digits,4))}</td>)}</tr>)}</tbody></table></div></details></>;
}
